// ─────────────────────────────────────────────────────────────────────────────
// CacheKey.test.ts — Tests for the cache key generator
// ─────────────────────────────────────────────────────────────────────────────

import { CacheKey, CACHE_KEY_PREFIX } from '../cache/CacheKey';

describe('CacheKey.generate()', () => {
  // ── Determinism ─────────────────────────────────────────────────────────────

  it('returns the same key for identical inputs', () => {
    const key1 = CacheKey.generate('GET', 'https://api.example.com/messages');
    const key2 = CacheKey.generate('GET', 'https://api.example.com/messages');
    expect(key1).toBe(key2);
  });

  it('always starts with the SDK prefix', () => {
    const key = CacheKey.generate('GET', '/api/feed');
    expect(key.startsWith(CACHE_KEY_PREFIX)).toBe(true);
  });

  // ── Method sensitivity ───────────────────────────────────────────────────────

  it('produces different keys for different HTTP methods on the same URL', () => {
    const getKey  = CacheKey.generate('GET',  '/api/messages');
    const postKey = CacheKey.generate('POST', '/api/messages');
    expect(getKey).not.toBe(postKey);
  });

  it('is case-insensitive on the method (GET === get)', () => {
    const upper = CacheKey.generate('GET', '/api/messages');
    const lower = CacheKey.generate('get', '/api/messages');
    expect(upper).toBe(lower);
  });

  // ── URL normalization ────────────────────────────────────────────────────────

  it('treats trailing-slash and no-trailing-slash URLs as the same', () => {
    const withSlash    = CacheKey.generate('GET', 'https://api.example.com/feed/');
    const withoutSlash = CacheKey.generate('GET', 'https://api.example.com/feed');
    expect(withSlash).toBe(withoutSlash);
  });

  it('treats query params in different order as the same URL', () => {
    const key1 = CacheKey.generate('GET', 'https://api.example.com/search?b=2&a=1');
    const key2 = CacheKey.generate('GET', 'https://api.example.com/search?a=1&b=2');
    expect(key1).toBe(key2);
  });

  it('produces different keys for different query param values', () => {
    const key1 = CacheKey.generate('GET', '/api/messages?since=100');
    const key2 = CacheKey.generate('GET', '/api/messages?since=999');
    expect(key1).not.toBe(key2);
  });

  it('handles relative URLs without throwing', () => {
    expect(() => CacheKey.generate('GET', '/api/relative')).not.toThrow();
  });

  it('gives the same key for equivalent relative URLs with trailing slash', () => {
    const key1 = CacheKey.generate('GET', '/api/feed/');
    const key2 = CacheKey.generate('GET', '/api/feed');
    expect(key1).toBe(key2);
  });

  // ── Body inclusion ────────────────────────────────────────────────────────────

  it('includes the request body in the key (POST-as-read pattern)', () => {
    const noBody   = CacheKey.generate('POST', '/graphql');
    const withBody = CacheKey.generate('POST', '/graphql', { query: '{ user { id } }' });
    expect(noBody).not.toBe(withBody);
  });

  it('produces different keys for different bodies on the same URL', () => {
    const key1 = CacheKey.generate('POST', '/graphql', { query: 'A' });
    const key2 = CacheKey.generate('POST', '/graphql', { query: 'B' });
    expect(key1).not.toBe(key2);
  });

  it('produces the same key for identical bodies regardless of JS object reference', () => {
    const body1 = { chat_id: 'c1', limit: 20 };
    const body2 = { chat_id: 'c1', limit: 20 };  // different object, same content
    expect(CacheKey.generate('GET', '/api/messages', body1))
      .toBe(CacheKey.generate('GET', '/api/messages', body2));
  });

  // ── Collision resistance ──────────────────────────────────────────────────────

  it('produces different keys for different URLs', () => {
    const keys = [
      CacheKey.generate('GET', '/api/messages'),
      CacheKey.generate('GET', '/api/feed'),
      CacheKey.generate('GET', '/api/users'),
      CacheKey.generate('GET', '/api/status'),
    ];
    const unique = new Set(keys);
    expect(unique.size).toBe(keys.length);
  });
});

// ── CacheKey.isSDKKey() ────────────────────────────────────────────────────────

describe('CacheKey.isSDKKey()', () => {
  it('returns true for keys generated by the SDK', () => {
    const key = CacheKey.generate('GET', '/api/messages');
    expect(CacheKey.isSDKKey(key)).toBe(true);
  });

  it('returns false for unrelated storage keys', () => {
    expect(CacheKey.isSDKKey('user_preferences')).toBe(false);
    expect(CacheKey.isSDKKey('redux_persist_root')).toBe(false);
    expect(CacheKey.isSDKKey('')).toBe(false);
  });

  it('uses the exported CACHE_KEY_PREFIX constant', () => {
    const key = `${CACHE_KEY_PREFIX}abc123`;
    expect(CacheKey.isSDKKey(key)).toBe(true);
  });
});
